[dynamodb]
table = "cmd-dev"
token_table = "cmd-dev-tokens"
region = "local"
access_key = "dev"
secret_key = "dev"
max_retries = 1

[store]
backend = "store.dynamodb"

[web]
listen_addr = "127.0.0.1:8080"

[auth0]
domain = "gl-cmd.auth0.com"
callback_url = "http://localhost:8080/_auth/callback"
logout_url = "http://localhost:8080/_auth/logout"

[mailgun]
domain = "gliderlabs.com"

[crypto]
secret_key = "somesupersecrettextorsomething"
