baseurl = "https://progrium.github.io/cmd/" #"https://www.cmd.io/"
languageCode = "en-us"
title = "Cmd.io Documentation"
theme = "www"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Digitalcraftsman"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = [
    "/css/dev.css"
  ]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "grey"
    	accent  = "light-blue"

    [params.font]
    	text = "Lato"
    	code = "Roboto Mono"


[social]
	twitter = ""
	github  = "gliderlabs/cmd"
	email   = "hello@email.com"


[[menu.main]]
	name   = "Material"
	url    = "docs/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "docs/getting-started/"
	weight = 10

[[menu.main]]
	name   = "Adding content"
	url    = "docs/adding-content/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "docs/roadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "docs/license/"
	weight = 40
