apiVersion: v1
kind: ConfigMap
metadata:
  name: beta-cmd-conf
data:
  config.toml: |-
    [docker]
    name = "_docker._tcp.sandbox.infra.gl"

    [store]
    backend = "store.dynamodb"

    [dynamodb]
    table = "beta.cmd.io_cmds"
    token_table = "beta.cmd.io_tokens"

    [sentry]
    environment = "beta"

    [auth0]
    domain = "gl-cmd.auth0.com"
    callback_url = "https://beta.cmd.io/_auth/callback"
    logout_url = "https://beta.cmd.io/_auth/logout"

    [mailgun]
    domain = "gliderlabs.com"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: beta-cmd-io
spec:
  replicas: 2
  revisionHistoryLimit: 4
  progressDeadlineSeconds: 90
  template:
    metadata:
      labels:
        app: cmd-io
        channel: beta
    spec:
      volumes:
        - name: host-key
          secret:
            secretName: beta-cmd-secrets
            items:
            - key: id_host
              path: id_host
        - name: config-volume
          configMap:
            name: beta-cmd-conf
      containers:
        - name: cmd
          image: 055471703963.dkr.ecr.us-east-1.amazonaws.com/cmd:${build}
          command: ["/usr/local/bin/cmd", "-d", "/config/config.toml"]
          ports:
            - name: http
              containerPort: 80
            - name: ssh
              containerPort: 22
          volumeMounts:
            - mountPath: /tmp/data/
              name: host-key
            - mountPath: /config
              name: config-volume
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: beta-cmd-secrets
                  key: sentry-dsn
            - name: CONSOLE_SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gliderlabs-secrets
                  key: slack-token
            - name: ACCESS_GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gliderlabs-secrets
                  key: github-token
            - name: DYNAMODB_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: beta-cmd-secrets
                  key: aws-access-key
            - name: DYNAMODB_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: beta-cmd-secrets
                  key: aws-secret-key
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: beta-cmd-secrets
                  key: auth0-client-id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: beta-cmd-secrets
                  key: auth0-client-secret

---
kind: Service
apiVersion: v1
metadata:
  name: beta-cmd
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:055471703963:certificate/5ce76820-c1b6-4bf3-b462-01bafa699232"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: cmd-io
    channel: beta
  ports:
    - name: http
      targetPort: http
      port: 80
    - name: https
      targetPort: http
      port: 443
    - name: ssh
      targetPort: ssh
      port: 22
