apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: beta-cmd-io
spec:
  replicas: 2
  revisionHistoryLimit: 4
  progressDeadlineSeconds: 90
  template:
    metadata:
      labels:
        app: cmd-io
        channel: beta
    spec:
      volumes:
        - name: host-key
          secret:
            secretName: beta-host-key
      containers:
        - name: cmd
          image: 055471703963.dkr.ecr.us-east-1.amazonaws.com/cmd:${build}
          ports:
            - name: http
              containerPort: 80
            - name: ssh
              containerPort: 22
          volumeMounts:
            - mountPath: "/tmp/data/"
              name: host-key
          env:
            - name: DOCKER_NAME
              value: _docker._tcp.sandbox.infra.gl
            - name: MAILGUN_DOMAIN
              value: gliderlabs.com
            - name: STORE_BACKEND
              value: store.dynamodb
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: cmd-sentry
                  key: dsn
            - name: SENTRY_ENVIRONMENT
              value: beta
            - name: CONSOLE_SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gliderlabs-slack
                  key: token
            - name: ACCESS_GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gliderlabs-github
                  key: token
            - name: DYNAMODB_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: beta-cmd-dynamodb
                  key: access-key
            - name: DYNAMODB_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: beta-cmd-dynamodb
                  key: secret-key
            - name: DYNAMODB_TABLE
              value: beta.cmd.io_cmds
            - name: DYNAMODB_TOKEN_TABLE
              value: beta.cmd.io_tokens
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: beta-cmd-auth0
                  key: client-id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: beta-cmd-auth0
                  key: client-secret
            - name: AUTH0_DOMAIN
              value: gl-cmd.auth0.com
            - name: AUTH0_CALLBACK_URL
              value: "https://beta.cmd.io/_auth/callback"
            - name: AUTH0_LOGOUT_URL
              value: "https://beta.cmd.io/_auth/logout"
---
kind: Service
apiVersion: v1
metadata:
  name: beta-cmd
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:055471703963:certificate/5ce76820-c1b6-4bf3-b462-01bafa699232"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: cmd-io
    channel: beta
  ports:
    - name: http
      targetPort: http
      port: 80
    - name: https
      targetPort: http
      port: 443
    - name: ssh
      targetPort: ssh
      port: 22
